#efi_general_nivel:
#    resource: "@EfiGeneralBundle/Controller/NivelController.php"
#    type:     annotation

efi_ganados:
    resource: "@EfiGanadosBundle/Resources/config/routing.yml"
    prefix:   /

efi_general:
    resource: "@EfiGeneralBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

logout:
    path:     /logout
    defaults: { _controller: EfiGeneralBundle:Security:logout }