# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    encoders:
#            Efi\GeneralBundle\Entity\Usuario:
#                algorithm: bcrypt
#    providers:
#            our_db_provider:
#                entity:
#                    class: EfiGeneralBundle:Usuario
#                    property: username
#                    # if you're using multiple entity managers
#                    # manager_name: customer
    providers:
        in_memory:
            memory:
                users:
                    18178032:
                        password: admin
                        roles: 'ROLE_USER'
                    18178031:
                        password: admin
                        roles: 'ROLE_ADMIN'
    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        login_firewall:
#                pattern:   ^/login$
#                anonymous: ~
        main:
            anonymous: ~
            form-login:
                login_path: login
                check_path: login
        secured_area:
            pattern:    ^/
            form_login: ~
            logout:
                path: /logout
                target: /login
        # disables authentication for assets and the profiler, adapt it according to your needs
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }