efi_ganados_persona:
    resource: "@EfiGanadosBundle/Resources/config/routing/persona.yml"
    prefix:   /persona/

efi_ganados_homepage:
    path:     /ganados/
    defaults: { _controller: EfiGanadosBundle:Default:index }
