efi_general_valorvariable:
    resource: "@EfiGeneralBundle/Resources/config/routing/valorvariable.yml"
    prefix:   /general/valorvariable/

efi_general_nivel:
    resource: "@EfiGeneralBundle/Resources/config/routing/nivel.yml"
    prefix:   /general/nivel/

efi_general_homepage:
    path:     /general/
    defaults: { _controller: EfiGeneralBundle:Default:index }

admin:
    path:     /admin
    defaults: { _controller: EfiGeneralBundle:Security:admin }

login:
    path:     /login
    defaults: { _controller: EfiGeneralBundle:Security:login }
    methods:  [GET, POST]

logout:
    path:     /logout
    defaults: { _controller: EfiGeneralBundle:Security:logout }
