efi_general_valorvariable:
    resource: "@EfiGeneralBundle/Resources/config/routing/valorvariable.yml"
    prefix:   /general/valorvariable/

efi_general_homepage:
    path:     /general/
    defaults: { _controller: EfiGeneralBundle:Default:index }



login:
    path:     /login/
    defaults: { _controller: EfiGeneralBundle:Security:login }

logout:
    path:     /logout
    defaults: { _controller: EfiGeneralBundle:Security:logout }
