nivel_index:
    path:     /{codigoPmi}/index.{_format}
    defaults: { _controller: "EfiGeneralBundle:Nivel:index", codigoPmi: 0, _format: html}
    methods:  GET
    requirements:
        _format:  json|html
#        _locale:  es