familia_index:
    path:     /{codigoPmi}/index.{_format}
    defaults: { _controller: "EfiGanadosBundle:Familia:index", codigoPmi: 0, _format: html}
    methods:  GET
    requirements:
        _format:  json|html|xml
#        _locale:  es

familia_show:
    path:     /{id}/show
    defaults: { _controller: "EfiGanadosBundle:Familia:show" }
    methods:  GET

familia_new:
    path:     /new
    defaults: { _controller: "EfiGanadosBundle:Familia:new" }
    methods:  [GET, POST]

familia_edit:
    path:     /{id}/edit
    defaults: { _controller: "EfiGanadosBundle:Familia:edit" }
    methods:  [GET, POST]

familia_delete:
    path:     /{id}/delete
    defaults: { _controller: "EfiGanadosBundle:Familia:delete" }
    methods:  DELETE
