familia_index:
    path:     /{codigoPmi}
    defaults: { _controller: "EfiGanadosBundle:Familia:index", codigoPmi: 0 }
    methods:  GET

familia_show:
    path:     /{id}/show
    defaults: { _controller: "EfiGanadosBundle:Familia:show" }
    methods:  GET

familia_new:
    path:     /new
    defaults: { _controller: "EfiGanadosBundle:Familia:new" }
    methods:  [GET, POST]

familia_edit:
    path:     /{id}/edit
    defaults: { _controller: "EfiGanadosBundle:Familia:edit" }
    methods:  [GET, POST]

familia_delete:
    path:     /{id}/delete
    defaults: { _controller: "EfiGanadosBundle:Familia:delete" }
    methods:  DELETE
